### PR TITLE
Look at data string and pick best guess parse format. Does not yet ha…

### PR DESCRIPTION
**Pull request by jsatchell**
…ndle case where optional seconds or minutes are absent.

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR! Sorry for the delay, I've disabled the mips targets so if you rebase it should pass and then be good to merge.

**Comment by jsatchell** [comment]
Now done the optional cases, where seconds or minutes are absent. I think the code now handles all the variants.

**Comment by XAMPPRocky** [comment]
Damn android, if you rebase again it should be good to go 🙂

**Comment by jsatchell** [comment]
Looks hopeful. In ideal world, we should have unit test coverage for all variants of everything.

**Comment by XAMPPRocky** [comment]
Thank you for your PR!

**Pull request merged**
