### PR TITLE
Split OID codec functionality in BER to be usable by other codecs

### PR DESCRIPTION
**Pull request by Nicceboy**
Other codecs seems to re-use bytepresentation of BER encoding for ObjectIdentifier type. 

This change would make it easier to access bytes without added length or tags.

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
> This change would make it easier to access bytes without added length or tags.

Thank you for your PR! Are you sure the length and tag should not be included other codecs? In the specs it's often cited as being a complete representation of the BER value, which would include tag and length.

**Comment by Nicceboy** [comment]
The existing functions are still there which can be used to get the tag and length as well, if required. I do not know all the codecs. I noticed that in UPER you used the tag and length at least. 

I compared to other implementations of OER and at least in this case they seems to drop. 
OER adds its own length determinant.

In standard it says that "***contents octets*** of BER encoding of the object identifier value" (specified in 8.19), so I would assume that is is without length and tags. 

In 8.19.5 section there is an example, which distincts contents

OBJECT IDENTIFIER | Length | Contents |
-|-|-|
06<sub>16</sub>| 03<sub>16</sub> | 883703<sub>16</sub>

**Comment by Nicceboy** [comment]
Seems like that similar wording is also used in PER. Apparently the logic should be the same but which one it is 😄

**Comment by Nicceboy** [comment]
I think this also applies for types `GeneralizedTime` and `UTCTime`. Should we split these functions in BER as well, or do helper functions outside of BER? Parsing the time strings would be identical.

**Comment by XAMPPRocky** [comment]
>  Should we split these functions in BER as well, or do helper functions outside of BER? Parsing the time strings would be identical.

In BER so it's clear that it's the BER encoding being used.

**Comment by XAMPPRocky** [comment]
Thank you for your PR!

**Pull request merged**
